# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_chairimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChairImage',
            new_name='ChairImages',
        ),
    ]
