# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20170705_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='photo',
        ),
    ]
